apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpaca
      ver: "2"
      env: test
  template:
    metadata:
      labels:
        app: alpaca
        ver: "2"
        env: test
    spec:
      containers:
        - name: alpaca-conatiner
          image: gcr.io/kuar-demo/kuard-amd64:green
          ports:
            - containerPort: 8080
              protocol: TCP
