# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "bento/ubuntu-22.04-arm64"
  config.vm.box = "net9/ubuntu-24.04-arm64"
  # config.vm.box_version ='20210924.0.0'
  config.vm.hostname = 'ansible'
  vm_name = 'ansible-arm-vm'
  config.vm.define vm_name

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network :private_network, ip: "172.17.8.112"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
    # vb.customize ["modifyhd", "--resize", 15 * 1024, "#{vb.name}.vdi"]
    # vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 0, '--device', 0, '--type', 'hdd', '--medium', "#{vb.name}.vdi"]
end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    set -e -x -u
    export DEBIAN_FRONTEND=noninteractive
    sudo timedatectl set-timezone Asia/Taipei
    export ARCH=$(dpkg --print-architecture)

    echo "================== Updating apt repository =================="
    sudo apt-get update

    echo "================== Setting locale to zh-TW =================="
    sudo sh -c 'echo "LANG=\"zh_TW.UTF-8\"" > /etc/default/locale'
    sudo locale-gen zh_TW zh_TW.UTF-8
    sudo apt-get install -y language-pack-zh-hant

    echo "================== Installing basic packages =================="
    sudo apt-get install -y ca-certificates curl gnupg lsb-release

    echo "================== set sshd configuration ===================="
    sudo /bin/bash << 'SCRIPT'
cat << 'EOF' >> /etc/ssh/sshd_config
PubkeyAuthentication yes
EOF
SCRIPT
    sudo systemctl daemon-reload
    # sudo systemctl restart sshd
    sudo systemctl restart ssh.socket
    sudo systemctl status ssh.socket
    if [ -f /vagrant/.ssh/id_rsa ]; then
      cp /vagrant/.ssh/id_rsa $HOME/.ssh/id_rsa   # Please prepare your SSH keys in /vagrant/.ssh inadvance.
    fi
    chown vagrant:vagrant $HOME/.ssh/id_rsa
    chmod 400 $HOME/.ssh/id_rsa
    cat /vagrant/.ssh/id_rsa.pub >> $HOME/.ssh/authorized_keys
    sudo mkdir -p /root/.ssh
    sudo cp /vagrant/.ssh/id_rsa /root/.ssh/id_rsa
    sudo chmod 400 /root/.ssh/id_rsa
    sudo cp $HOME/.ssh/authorized_keys /root/.ssh/authorized_keys

    echo "================== Install zsh =============================="
    sudo apt-get install -y zsh

    echo "================== Install Meslo Nerd Fonts ======================================"
    sudo mkdir -p /usr/local/share/fonts/MesloNerdFonts
    sudo wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf -P /usr/local/share/fonts/MesloNerdFonts
    sudo wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf -P /usr/local/share/fonts/MesloNerdFonts
    sudo wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf -P /usr/local/share/fonts/MesloNerdFonts
    sudo wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf -P /usr/local/share/fonts/MesloNerdFonts

    echo "================== Install oh-my-zsh and related plug-ins ========================"
    sudo apt-get install -y fonts-powerline
    wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    sh install.sh
    sudo cp -rfp $HOME/.oh-my-zsh /root
    sudo chown -R root:root /root/.oh-my-zsh

    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
        ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
    ln -s ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k ${ZSH_CUSTOM:-$HOME/.oh-my-zsh}/themes/powerlevel10k
    git clone https://github.com/zsh-users/zsh-completions \
        ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-completions
    git clone https://github.com/zsh-users/zsh-autosuggestions \
        ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-syntax-highlighting \
        ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

    sed -i 's|plugins=(git)|plugins=(git zsh-autosuggestions zsh-completions zsh-syntax-highlighting)|g' $HOME/.zshrc
    sed -i 's|ZSH_THEME="robbyrussell"|ZSH_THEME="powerlevel10k/powerlevel10k"|g' $HOME/.zshrc
    sudo chsh -s /bin/zsh vagrant

    sudo git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
        /root/.oh-my-zsh/custom/themes/powerlevel10k
    sudo ln -s /root/.oh-my-zsh/custom/themes/powerlevel10k /root/.oh-my-zsh/themes/powerlevel10k
    sudo git clone https://github.com/zsh-users/zsh-completions \
        /root/.oh-my-zsh/custom/plugins/zsh-completions
    sudo git clone https://github.com/zsh-users/zsh-autosuggestions \
        /root/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    sudo git clone https://github.com/zsh-users/zsh-syntax-highlighting \
        /root/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    sudo cp $HOME/.zshrc /root/.zshrc
    sudo chown root:root /root/.zshrc

    echo "================== Set IPv4 IP Forward ===================="
    sudo /bin/bash << 'SCRIPT'
cat << 'EOF' >> /etc/sysctl.conf
net.ipv4.ip_forward=1
EOF
SCRIPT
    sudo sysctl -p

    echo "================== Installing containerd.io ==============="
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo "deb [arch=${ARCH} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update && sudo apt-get install -y containerd.io
    sudo containerd config default | sudo tee /etc/containerd/config.toml
    if grep -q 'SystemdCgroup = false' /etc/containerd/config.toml; then
      sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
    fi
    sudo systemctl daemon-reload
    sudo systemctl enable containerd
    sudo systemctl restart containerd

    echo "================== Installing CNI plugins ================="
    export CNI_VERSION="1.6.1"
    wget https://github.com/containernetworking/plugins/releases/download/v${CNI_VERSION}/cni-plugins-linux-${ARCH}-v${CNI_VERSION}.tgz
    sudo mkdir -p /opt/cni/bin
    sudo tar Cxzvf /opt/cni/bin cni-plugins-linux-${ARCH}-v${CNI_VERSION}.tgz

    echo "================== Installing nerdctl ====================="
    export NERDCTL_VERSION="2.0.2"
    wget https://github.com/containerd/nerdctl/releases/download/v${NERDCTL_VERSION}/nerdctl-${NERDCTL_VERSION}-linux-${ARCH}.tar.gz
    sudo tar Cxzvvf /usr/local nerdctl-${NERDCTL_VERSION}-linux-${ARCH}.tar.gz

    echo "================== Installing Kubernetes =================="
    sudo /bin/bash << 'SCRIPT'
cat << 'EOF' >> /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
SCRIPT
    sudo sysctl --system
    sudo modprobe br_netfilter

    export K8S_MAIN_VERSION="1.32"
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v${K8S_MAIN_VERSION}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes.gpg
    sudo sh -c "echo deb [arch=${ARCH} signed-by=/etc/apt/keyrings/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v${K8S_MAIN_VERSION}/deb/ / \ > /etc/apt/sources.list.d/kubernetes.list"
    sudo apt-get update
    export K8S_VERSION="${K8S_MAIN_VERSION}.0-1.1"
    sudo apt-get install -y kubeadm=${K8S_VERSION} kubectl=${K8S_VERSION} kubelet=${K8S_VERSION}
    sudo apt-mark hold kubeadm kubectl kubelet

    echo "================== Disable swap =================="
    # https://github.com/kubernetes/kubernetes/issues/53533
    sudo swapoff -a && sudo sysctl -w vm.swappiness=0
    sudo sed -i '/swap/s/^/#/' /etc/fstab
    sudo sed '/vagrant--vg-swap/d' -i /etc/fstab

    echo "================== Start Kubernetes Cluster =================="
    sudo kubeadm init
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
    sudo mkdir -p /root/.kube
    sudo cp -i /etc/kubernetes/admin.conf /root/.kube/config
    sudo chown root:root /root/.kube/config

    echo "================== Install Calico to handle network policy =================="
    kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

    echo "===== Untaint the master node so we can deploy workers for single node on VirtualBox VM ====="
    kubectl taint nodes --all node-role.kubernetes.io/control-plane-

    # echo "================== Install Kubernetes Dashboard =================="
    # export K8S_DASHBOARD_VERSION="2.7.0"
    # kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v${K8S_DASHBOARD_VERSION}/aio/deploy/recommended.yaml

    # echo "================== Start dnsutils Pod =================="
    # kubectl apply -f https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/admin/dns/dnsutils.yaml

    # echo "================== Install mini-conda =================="
    # mkdir -p ${HOME}/miniconda3
    # # 設定架構名稱
    # export ARCH_NAME="x86_64"  # 預設值
    # case "${ARCH}" in
    #     arm64)
    #         ARCH_NAME="aarch64"
    #         ;;
    #     amd64|x86_64)
    #         ARCH_NAME="x86_64"
    #         ;;
    #     i386|i686)
    #         ARCH_NAME="x86"
    #         ;;
    #     ppc64el)
    #         ARCH_NAME="ppc64le"
    #         ;;
    #     s390x)
    #         ARCH_NAME="s390x"
    #         ;;
    #     armhf)
    #         ARCH_NAME="armv7l"
    #         ;;
    #     sparcv9)
    #         ARCH_NAME="sparc_v9"
    #         ;;
    #     *)
    #         echo "Unknown architecture: ${ARCH}"
    #         ;;
    # esac
    # wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-${ARCH_NAME}.sh -O ${HOME}/miniconda3.sh
    # bash ${HOME}/miniconda3.sh -b -u -p ${HOME}/miniconda3
    # rm -f ${HOME}/miniconda3.sh
    # source ${HOME}/miniconda3/bin/activate
    # conda init --all

    echo "================== Installing Python components =================="
    sudo apt-get install -y python3-pip python3-venv python3-dev build-essential libssl-dev libffi-dev python3-setuptools

    echo "================== addtional install - Helm and NodeJS ======================="
    sudo curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    sudo sh -c "echo deb [arch=${ARCH} signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main \ > /etc/apt/sources.list.d/helm.list"
    sudo apt-get update
    sudo apt-get install helm
    helm plugin install https://github.com/databus23/helm-diff

    echo "================== Installing Ansible Requirements =================="
    # conda create -n ansible -y
    # conda activate ansible
    python3 -m venv /home/vagrant/ansible
    source /home/vagrant/ansible/bin/activate
    pip install -r /vagrant/requirements.txt
    deactivate
    # conda deactivate
 
    echo "================== ansible-vm Provisioning Finished =================="
  SHELL
end
