# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/focal64"
  # config.vm.box_version ='20210924.0.0'
  config.vm.hostname = 'ansible'
  config.vm.define vm_name = 'ansible-vm'

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network :private_network, ip: "172.17.8.112"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    set -e -x -u
    export DEBIAN_FRONTEND=noninteractive

    echo "================== Updating apt repository =================="
    sudo apt-get update

    echo "================== set sshd configuration ===================="
    sudo /bin/bash << 'SCRIPT'
cat << 'EOF' >> /etc/ssh/sshd_config
PubkeyAuthentication yes
EOF
SCRIPT
    sudo systemctl daemon-reload
    sudo systemctl restart sshd
    mkdir -p $HOME/.ssh
    cp /vagrant/.ssh/id_rsa $HOME/.ssh/id_rsa   # Please prepare your SSH keys in /vagrant/.ssh inadvance.
    chown vagrant:vagrant $HOME/.ssh/id_rsa
    chmod 400 $HOME/.ssh/id_rsa
    cat /vagrant/.ssh/id_rsa.pub >> $HOME/.ssh/authorized_keys
    sudo mkdir -p /root/.ssh
    sudo cp /vagrant/.ssh/id_rsa /root/.ssh/id_rsa
    sudo cp /vagrant/.ssh/authorized_keys /root/.ssh/authorized_keys
    sudo chmod 400 /root/.ssh/id_rsa

    echo "================== Install zsh =============================="
    sudo apt-get install -y zsh
    sudo sh -c 'echo "LANG=\"zh_TW.UTF-8\"" > /etc/default/locale'
    sudo locale-gen zh_TW zh_TW.UTF-8
    sudo apt-get install -y language-pack-zh-hant

    echo "================== Install Meslo Nerd Fonts ======================================"
    sudo mkdir -p /usr/local/share/fonts/MesloNerdFonts
    sudo wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf -P /usr/local/share/fonts/MesloNerdFonts
    sudo wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf -P /usr/local/share/fonts/MesloNerdFonts
    sudo wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf -P /usr/local/share/fonts/MesloNerdFonts
    sudo wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf -P /usr/local/share/fonts/MesloNerdFonts

    echo "================== Install oh-my-zsh and related plug-ins ========================"
    sudo apt-get install -y fonts-powerline
    wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    sh install.sh
    sudo cp -rfp $HOME/.oh-my-zsh /root
    sudo chown -R root:root /root/.oh-my-zsh

    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
        ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
    ln -s ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k ${ZSH_CUSTOM:-$HOME/.oh-my-zsh}/themes/powerlevel10k
    git clone https://github.com/zsh-users/zsh-completions \
        ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-completions
    git clone https://github.com/zsh-users/zsh-autosuggestions \
        ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-syntax-highlighting \
        ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

    sudo timedatectl set-timezone Asia/Taipei
    sed -i 's|plugins=(git)|plugins=(git zsh-autosuggestions zsh-completions zsh-syntax-highlighting)|g' $HOME/.zshrc
    sed -i 's|ZSH_THEME="robbyrussell"|ZSH_THEME="powerlevel10k/powerlevel10k"|g' $HOME/.zshrc
    sudo chsh -s /bin/zsh vagrant

    sudo git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
        /root/.oh-my-zsh/custom/themes/powerlevel10k
    sudo ln -s /root/.oh-my-zsh/custom/themes/powerlevel10k /root/.oh-my-zsh/themes/powerlevel10k
    sudo git clone https://github.com/zsh-users/zsh-completions \
        /root/.oh-my-zsh/custom/plugins/zsh-completions
    sudo git clone https://github.com/zsh-users/zsh-autosuggestions \
        /root/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    sudo git clone https://github.com/zsh-users/zsh-syntax-highlighting \
        /root/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    sudo cp $HOME/.zshrc /root/.zshrc
    sudo chown root:root /root/.zshrc

    echo "================== Installing Docker =================="
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker.gpg
    sudo sh -c "echo deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable \ > /etc/apt/sources.list.d/docker.list"
    sudo apt-get update
    export DOCKER_VERSION="5:20.10.13~3-0~ubuntu-focal"
    sudo apt-get install -y docker-ce=$DOCKER_VERSION docker-ce-cli=$DOCKER_VERSION containerd.io
    sudo usermod -aG docker $USER
    sudo apt-mark hold docker-ce docker-ce-cli containerd.io

    echo "============== Set Cgroup driver to systemd ==============="
    sudo mkdir -p /etc/docker/
    sudo /bin/bash << 'SCRIPT'
cat << 'EOF' >> /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=systemd"]
}
EOF
SCRIPT

    echo "================== Set IPv4 IP Forward ===================="
    sudo /bin/bash << 'SCRIPT'
cat << 'EOF' >> /etc/sysctl.conf
net.ipv4.ip_forward=1
EOF
SCRIPT
    sudo sysctl -p

    echo "================== Enable Docker Engine ===================="
    sudo systemctl enable docker
    sudo systemctl daemon-reload
    sudo systemctl restart docker

    echo "================== Installing Kubernetes =================="
    sudo /bin/bash << 'SCRIPT'
cat << 'EOF' >> /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
SCRIPT
    sudo sysctl --system

    curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/kubernetes.gpg
    sudo sh -c "echo deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/kubernetes.gpg] https://apt.kubernetes.io/ kubernetes-xenial main \ > /etc/apt/sources.list.d/kubernetes.list"
    sudo apt-get update
    export K8S_VERSION="1.23.6"
    sudo apt-get install -y kubeadm=${K8S_VERSION}-00 kubectl=${K8S_VERSION}-00 kubelet=${K8S_VERSION}-00
    sudo apt-mark hold kubeadm kubectl kubelet
    echo 'kubectl completion zsh | sudo tee /etc/bash_completion.d/kubectl > /dev/null' >> $HOME/.zshrc

    echo "================== Disable swap =================="
    # https://github.com/kubernetes/kubernetes/issues/53533
    sudo swapoff -a && sudo sysctl -w vm.swappiness=0
    sudo sed '/vagrant--vg-swap/d' -i /etc/fstab

    git clone https://gitlab.com/m070888/installk8s/

    echo "================== Start Kubernetes Cluster =================="
    sudo kubeadm init
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
    sudo mkdir -p /root/.kube
    sudo cp -i /etc/kubernetes/admin.conf /root/.kube/config
    sudo chown root:root /root/.kube/config

    echo "================== Install Calico to handle network policy =================="
    sed -i 's/vlan.206/enp0s8/g' ./installk8s/master/5calico/calico.yaml
    kubectl apply -f ./installk8s/master/5calico/calico.yaml
    
    echo "===== Untaint the master node so we can deploy workers for single node on VirtualBox VM ====="
    kubectl taint nodes --all node-role.kubernetes.io/master-

    echo "================== Install Kubernetes Dashboard =================="
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.3.1/aio/deploy/recommended.yaml

    echo "================== Start dnsutils Pod =================="
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/admin/dns/dnsutils.yaml

    echo "================== Installing Python components =================="
    sudo apt-get install -y python3 python3-pip python3-dev

    echo "================== Installing Ansible Requirements =================="
    sudo pip install -r /vagrant/requirements.txt
    
    echo "================== addtional install - yq, Helm and NodeJS ======================="
    sudo apt install -y jq

    sudo curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    sudo sh -c "echo deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main \ > /etc/apt/sources.list.d/helm.list"
    sudo apt-get update
    sudo apt-get install helm

    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    sudo apt-get install nodejs
    node --version
    npm version
    sudo npm install -g typescript shx pkg

    echo "================== ansible-vm Provisioning Finished =================="
  SHELL
end
